/* eslint-disable @typescript-eslint/no-explicit-any */
/**
 * Client-side Excel export. Model-type tools (DCF, comps, SIP, risk, correlation, DuPont) become
 * live spreadsheets: blue cells are inputs, black cells are formulas, so users can change an
 * assumption and watch the model recalculate. Other tools export as clean data sheets.
 * exceljs is loaded on demand so it never weighs down the chat page.
 */
import type ExcelJS from "exceljs";
import { TOOL_LABELS } from "./followups";

type WS = ExcelJS.Worksheet;
type WB = ExcelJS.Workbook;

const INPUT_FONT = { color: { argb: "FF1F4ED8" }, bold: true };
const INPUT_FILL: ExcelJS.Fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FFFFF7D6" } };
const HEAD_FILL: ExcelJS.Fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FF0B6E4E" } };
const HEAD_FONT = { color: { argb: "FFFFFFFF" }, bold: true };
const PCT = "0.00%";
const NUM = "#,##0.00";
const BIG = "#,##0";

const safeName = (s: string) => s.replace(/[\\/*?:[\]]/g, " ").slice(0, 31).trim() || "Sheet";

function uniqueSheet(wb: WB, name: string): WS {
  let n = safeName(name), k = 2;
  while (wb.getWorksheet(n)) n = safeName(`${name.slice(0, 27)} ${k++}`);
  return wb.addWorksheet(n);
}

function title(ws: WS, text: string, sub: string) {
  ws.getCell("A1").value = text;
  ws.getCell("A1").font = { bold: true, size: 14 };
  ws.getCell("A2").value = `${sub} · Generated by Nazar on ${new Date().toLocaleString()} · Source: Yahoo Finance (may be delayed) · We explain; you decide. Not investment advice`;
  ws.getCell("A2").font = { italic: true, color: { argb: "FF6B7280" }, size: 9 };
}

function header(ws: WS, row: number, labels: string[], startCol = 1) {
  labels.forEach((l, i) => {
    const c = ws.getCell(row, startCol + i);
    c.value = l;
    c.fill = HEAD_FILL;
    c.font = HEAD_FONT;
    c.alignment = { horizontal: i === 0 ? "left" : "right" };
  });
}

function input(ws: WS, addr: string, value: any, fmt?: string) {
  const c = ws.getCell(addr);
  c.value = value ?? null;
  c.font = INPUT_FONT;
  c.fill = INPUT_FILL;
  if (fmt) c.numFmt = fmt;
}

function formula(ws: WS, addr: string, f: string, result?: any, fmt?: string, bold = false) {
  const c = ws.getCell(addr);
  c.value = { formula: f, result: result ?? undefined } as any;
  if (fmt) c.numFmt = fmt;
  if (bold) c.font = { bold: true };
}

function label(ws: WS, addr: string, text: string, bold = false) {
  ws.getCell(addr).value = text;
  if (bold) ws.getCell(addr).font = { bold: true };
}

const col = (n: number) => {
  let s = "";
  for (n++; n > 0; n = Math.floor((n - 1) / 26)) s = String.fromCharCode(65 + ((n - 1) % 26)) + s;
  return s;
};

/* ------------------------------ Models ------------------------------ */

function dcf(wb: WB, d: any) {
  const ws = uniqueSheet(wb, `DCF ${d.symbol}`);
  const a = d.assumptions;
  title(ws, `${d.symbol} · Discounted cash flow model (${d.currency})`, d.fxConversion ? `Financials converted from ${d.fxConversion.from} at ${d.fxConversion.rate}` : "All amounts in trading currency");
  label(ws, "A4", "Inputs (blue cells are editable)", true);
  const rows: [string, any, string][] = [
    ["Trailing free cash flow", a.fcf, BIG],
    ["FCF growth, years 1–N", a.growthRate, PCT],
    ["Discount rate (WACC)", a.discountRate, PCT],
    ["Terminal growth", a.terminalGrowth, PCT],
    ["Cash", a.cash, BIG],
    ["Debt", a.debt, BIG],
    ["Shares outstanding", a.shares, BIG],
    ["Current share price", d.price, NUM],
    ["Projection years (N)", a.years, "0"],
  ];
  rows.forEach(([l, v, f], i) => { label(ws, `A${5 + i}`, l); input(ws, `B${5 + i}`, v, f); });
  // B5 FCF, B6 g, B7 r, B8 tg, B9 cash, B10 debt, B11 shares, B12 price, B13 N
  const start = 16;
  header(ws, start - 1, ["Year", "Projected FCF", "Discount factor", "Present value"]);
  const N = a.years as number;
  for (let k = 0; k < N; k++) {
    const r = start + k, p = d.projections?.[k];
    ws.getCell(`A${r}`).value = k + 1;
    formula(ws, `B${r}`, k === 0 ? `$B$5*(1+$B$6)` : `B${r - 1}*(1+$B$6)`, p?.fcf, BIG);
    formula(ws, `C${r}`, `1/(1+$B$7)^A${r}`, p ? p.pv / p.fcf : undefined, "0.0000");
    formula(ws, `D${r}`, `B${r}*C${r}`, p?.pv, BIG);
  }
  const last = start + N - 1, s = last + 2;
  label(ws, `A${s}`, "Sum of PV of FCF"); formula(ws, `B${s}`, `SUM(D${start}:D${last})`, d.breakdown?.pvFcf, BIG);
  label(ws, `A${s + 1}`, "Terminal value (Gordon growth)"); formula(ws, `B${s + 1}`, `B${last}*(1+$B$8)/($B$7-$B$8)`, undefined, BIG);
  label(ws, `A${s + 2}`, "PV of terminal value"); formula(ws, `B${s + 2}`, `B${s + 1}/(1+$B$7)^A${last}`, d.breakdown?.pvTerminal, BIG);
  label(ws, `A${s + 3}`, "Plus cash, less debt"); formula(ws, `B${s + 3}`, `$B$9-$B$10`, d.breakdown?.netCash, BIG);
  label(ws, `A${s + 4}`, "Equity value", true); formula(ws, `B${s + 4}`, `B${s}+B${s + 2}+B${s + 3}`, d.breakdown?.equity, BIG, true);
  label(ws, `A${s + 5}`, "Intrinsic value per share", true); formula(ws, `B${s + 5}`, `B${s + 4}/$B$11`, d.intrinsicValue, NUM, true);
  label(ws, `A${s + 6}`, "Upside vs current price", true); formula(ws, `B${s + 6}`, `B${s + 5}/$B$12-1`, d.upside, PCT, true);

  // Sensitivity: closed-form per-share value for each (WACC, growth) pair, all live formulas.
  const t = s + 9;
  label(ws, `A${t - 1}`, "Sensitivity: value per share (rows: WACC, columns: FCF growth; edit the blue headers)", true);
  const gs: number[] = d.sensitivity?.growthRates ?? [];
  const rs: number[] = d.sensitivity?.discountRates ?? [];
  gs.forEach((g, j) => input(ws, `${col(j + 1)}${t}`, g, PCT));
  rs.forEach((r, i) => {
    const row = t + 1 + i;
    input(ws, `A${row}`, r, PCT);
    gs.forEach((_, j) => {
      const G = `${col(j + 1)}$${t}`, R = `$A${row}`, q = `((1+${G})/(1+${R}))`;
      // When growth = discount rate the geometric series degenerates to FCF × N.
      const pvFcf = `IF(${G}=${R},$B$5*$B$13,$B$5*${q}*(1-${q}^$B$13)/(1-${q}))`;
      formula(ws, `${col(j + 1)}${row}`, `IFERROR((${pvFcf}+$B$5*(1+${G})^$B$13*(1+$B$8)/(${R}-$B$8)/(1+${R})^$B$13+$B$9-$B$10)/$B$11,"")`, d.sensitivity?.grid?.[i]?.[j] ?? undefined, NUM);
    });
  });
  ws.getColumn(1).width = 44;
  for (let c = 2; c <= 7; c++) ws.getColumn(c).width = 18;
}

function comps(wb: WB, d: any) {
  const ws = uniqueSheet(wb, `Comps ${d.symbol}`);
  title(ws, `${d.symbol} · Comparable company valuation (${d.currency})`, d.fxNote ?? "Multiples from Yahoo Finance");
  const mult = ["trailingPE", "forwardPE", "evToEbitda", "priceToBook", "priceToSales"];
  header(ws, 4, ["Company", "Ticker", "P/E (TTM)", "Forward P/E", "EV/EBITDA", "P/B", "P/S"]);
  const rowsAll = [d.target, ...d.peers];
  rowsAll.forEach((r: any, i: number) => {
    const row = 5 + i;
    ws.getCell(`A${row}`).value = i === 0 ? `${r.name} (target)` : r.name;
    ws.getCell(`B${row}`).value = r.symbol;
    mult.forEach((k, j) => input(ws, `${col(2 + j)}${row}`, r[k], "0.00"));
    if (i === 0) ws.getRow(row).font = { bold: true };
  });
  const p0 = 6, p1 = 5 + rowsAll.length - 1, medRow = p1 + 1;
  label(ws, `A${medRow}`, "Peer median (excl. target)", true);
  mult.forEach((k, j) => formula(ws, `${col(2 + j)}${medRow}`, `IFERROR(MEDIAN(${col(2 + j)}${p0}:${col(2 + j)}${p1}),"")`, d.medians?.[k] ?? undefined, "0.00", true));

  const b = medRow + 3;
  label(ws, `A${b - 1}`, "Target inputs (blue cells are editable)", true);
  const ins: [string, any, string][] = [
    ["EPS (TTM)", d.inputs.trailingEps, NUM], ["EPS (forward)", d.inputs.forwardEps, NUM], ["EBITDA", d.inputs.ebitda, BIG],
    ["Net debt (debt − cash)", d.netDebt, BIG], ["Book value per share", d.inputs.bookValue, NUM], ["Revenue", d.inputs.revenue, BIG],
    ["Shares outstanding", d.shares, BIG], ["Current share price", d.price, NUM],
  ];
  ins.forEach(([l, v, f], i) => { label(ws, `A${b + i}`, l); input(ws, `B${b + i}`, v, f); });
  // B(b) EPS, b+1 fwd EPS, b+2 EBITDA, b+3 net debt, b+4 BVPS, b+5 revenue, b+6 shares, b+7 price
  const m = b + 10;
  header(ws, m - 1, ["Method", "Peer median", "Implied price"]);
  const methods: [string, string, string, string][] = [
    ["P/E × EPS", "C", `B${m}*$B$${b}`, "trailingPE"],
    ["Forward P/E × forward EPS", "D", `B${m + 1}*$B$${b + 1}`, "forwardPE"],
    ["EV/EBITDA (less net debt) ÷ shares", "E", `(B${m + 2}*$B$${b + 2}-$B$${b + 3})/$B$${b + 6}`, "evToEbitda"],
    ["P/B × book value per share", "F", `B${m + 3}*$B$${b + 4}`, "priceToBook"],
    ["P/S × revenue ÷ shares", "G", `B${m + 4}*$B$${b + 5}/$B$${b + 6}`, "priceToSales"],
  ];
  methods.forEach(([l, c, f, k], i) => {
    const row = m + i;
    label(ws, `A${row}`, l);
    formula(ws, `B${row}`, `${c}${medRow}`, d.medians?.[k], "0.00");
    formula(ws, `C${row}`, `IFERROR(${f},"")`, d.implied?.[k] ?? undefined, NUM);
  });
  label(ws, `A${m + 5}`, "Blended fair value (average of methods)", true);
  formula(ws, `C${m + 5}`, `AVERAGEIF(C${m}:C${m + 4},">0")`, d.blended, NUM, true);
  label(ws, `A${m + 6}`, "Upside vs current price", true);
  formula(ws, `C${m + 6}`, `C${m + 5}/$B$${b + 7}-1`, d.upside, PCT, true);
  ws.getColumn(1).width = 42;
  for (let c = 2; c <= 7; c++) ws.getColumn(c).width = 16;
}

function sip(wb: WB, d: any) {
  const ws = uniqueSheet(wb, `SIP ${d.symbol}`);
  title(ws, `${d.symbol} · SIP backtest (${d.currency})`, `${d.installments} monthly instalments over ${d.years} years`);
  label(ws, "A4", "Monthly amount"); input(ws, "B4", d.monthlyAmount, NUM);
  label(ws, "A5", "Latest price"); input(ws, "B5", d.lastPrice, NUM);
  const h = 8;
  header(ws, h, ["Month", "Price", "Amount", "Units bought", "Cumulative units", "Invested to date", "Value at month-end price"]);
  d.schedule.forEach((r: any, i: number) => {
    const row = h + 1 + i;
    ws.getCell(`A${row}`).value = new Date(r.date);
    ws.getCell(`A${row}`).numFmt = "mmm yyyy";
    input(ws, `B${row}`, r.price, NUM);
    formula(ws, `C${row}`, `$B$4`, d.monthlyAmount, NUM);
    formula(ws, `D${row}`, `C${row}/B${row}`, r.units, "0.0000");
    formula(ws, `E${row}`, i === 0 ? `D${row}` : `E${row - 1}+D${row}`, r.cumulativeUnits, "0.0000");
    formula(ws, `F${row}`, i === 0 ? `C${row}` : `F${row - 1}+C${row}`, r.invested, NUM);
    formula(ws, `G${row}`, `E${row}*B${row}`, r.value, NUM);
    // Cash flows for XIRR
    ws.getCell(`I${row}`).value = new Date(r.date);
    ws.getCell(`I${row}`).numFmt = "dd-mmm-yyyy";
    formula(ws, `J${row}`, `-C${row}`, -d.monthlyAmount, NUM);
  });
  const last = h + d.schedule.length, fin = last + 1;
  ws.getCell(`I${h}`).value = "Cash-flow date";
  ws.getCell(`J${h}`).value = "Cash flow";
  [ `I${h}`, `J${h}` ].forEach((a) => { ws.getCell(a).fill = HEAD_FILL; ws.getCell(a).font = HEAD_FONT; });
  ws.getCell(`I${fin}`).value = new Date();
  ws.getCell(`I${fin}`).numFmt = "dd-mmm-yyyy";
  formula(ws, `J${fin}`, `E${last}*$B$5`, d.value, NUM);
  const s = 4;
  label(ws, `D${s}`, "Total invested", true); formula(ws, `E${s}`, `SUM(C${h + 1}:C${last})`, d.invested, NUM, true);
  label(ws, `D${s + 1}`, "Current value", true); formula(ws, `E${s + 1}`, `E${last}*$B$5`, d.value, NUM, true);
  label(ws, `D${s + 2}`, "Gain", true); formula(ws, `E${s + 2}`, `E${s + 1}-E${s}`, d.gain, NUM, true);
  label(ws, `F${s}`, "Absolute return", true); formula(ws, `G${s}`, `E${s + 1}/E${s}-1`, d.absoluteReturn, PCT, true);
  label(ws, `F${s + 1}`, "XIRR (annualised)", true); formula(ws, `G${s + 1}`, `XIRR(J${h + 1}:J${fin},I${h + 1}:I${fin})`, d.xirr, PCT, true);
  label(ws, `F${s + 2}`, "Lump sum at start instead", true); formula(ws, `G${s + 2}`, `E${s}/B${h + 1}*$B$5`, d.lumpSum?.value, NUM, true);
  [1, 2, 3, 4, 5, 6, 7, 9, 10].forEach((c) => (ws.getColumn(c).width = c === 1 || c === 4 || c === 6 ? 24 : 16));
}

function risk(wb: WB, d: any) {
  const ws = uniqueSheet(wb, `Risk ${d.symbol}`);
  title(ws, `${d.symbol} vs ${d.benchmark} · Risk & return (${d.range}, ${d.interval === "1d" ? "daily" : "weekly"})`, "Returns from adjusted closes");
  const h = 14, first = h + 1, last = h + d.prices.length;
  header(ws, h, ["Date", d.symbol, d.benchmark, `${d.symbol} return`, `${d.benchmark} return`, "Running peak", "Drawdown"]);
  d.prices.forEach(([date, a, b]: [string, number, number], i: number) => {
    const row = first + i;
    ws.getCell(`A${row}`).value = new Date(date);
    ws.getCell(`A${row}`).numFmt = "dd-mmm-yyyy";
    input(ws, `B${row}`, a, NUM);
    input(ws, `C${row}`, b, NUM);
    if (i > 0) {
      formula(ws, `D${row}`, `B${row}/B${row - 1}-1`, a / d.prices[i - 1][1] - 1, "0.00%");
      formula(ws, `E${row}`, `C${row}/C${row - 1}-1`, b / d.prices[i - 1][2] - 1, "0.00%");
    }
    formula(ws, `F${row}`, i === 0 ? `B${row}` : `MAX(F${row - 1},B${row})`, undefined, NUM);
    formula(ws, `G${row}`, `B${row}/F${row}-1`, undefined, "0.00%");
  });
  const R = `D${first + 1}:D${last}`, B = `E${first + 1}:E${last}`;
  label(ws, "A4", "Periods per year"); input(ws, "B4", d.interval === "1d" ? 252 : 52, "0");
  label(ws, "A5", "Risk-free rate"); input(ws, "B5", d.riskFree, PCT);
  label(ws, "A6", "Years"); formula(ws, "B6", `(A${last}-A${first})/365.25`, undefined, "0.00");
  const st = d.stats;
  const out: [string, string, string, any, string][] = [
    ["D4", "CAGR", `(B${last}/B${first})^(1/B6)-1`, st.cagr, PCT],
    ["D5", "Benchmark CAGR", `(C${last}/C${first})^(1/B6)-1`, st.benchmarkCagr, PCT],
    ["D6", "Volatility (annualised)", `STDEV.S(${R})*SQRT(B4)`, st.volatility, PCT],
    ["D7", "Sharpe ratio", `(E4-B5)/E6`, st.sharpe, "0.00"],
    ["D8", "Beta", `SLOPE(${R},${B})`, st.beta, "0.00"],
    ["D9", "Correlation", `CORREL(${R},${B})`, st.correlation, "0.00"],
    ["D10", "Alpha (Jensen, annual)", `E4-(B5+E8*(E5-B5))`, st.alpha, PCT],
    ["D11", "Max drawdown", `MIN(G${first}:G${last})`, st.maxDrawdown, PCT],
  ];
  out.forEach(([addr, l, f, v, fmt]) => { label(ws, addr, l, true); formula(ws, addr.replace("D", "E"), f, v, fmt, true); });
  [14, 16, 16, 24, 16, 16, 14].forEach((w, i) => (ws.getColumn(i + 1).width = w));
}

function correlation(wb: WB, d: any) {
  const px = uniqueSheet(wb, "Correlation prices");
  const n = d.symbols.length;
  title(px, `Prices for correlation (${d.range}, ${d.interval === "1d" ? "daily" : "weekly"})`, "Adjusted closes on common trading dates");
  header(px, 4, ["Date", ...d.symbols]);
  d.prices.forEach((r: any[], i: number) => {
    px.getCell(`A${5 + i}`).value = new Date(r[0]);
    px.getCell(`A${5 + i}`).numFmt = "dd-mmm-yyyy";
    r.slice(1).forEach((v: number, j: number) => input(px, `${col(j + 1)}${5 + i}`, v, NUM));
  });
  const first = 5, last = 4 + d.prices.length;
  header(px, 4, d.symbols.map((s: string) => `${s} return`), n + 3);
  for (let i = first + 1; i <= last; i++) d.symbols.forEach((_: string, j: number) => formula(px, `${col(n + 2 + j)}${i}`, `${col(j + 1)}${i}/${col(j + 1)}${i - 1}-1`, undefined, "0.00%"));
  const ws = uniqueSheet(wb, "Correlation matrix");
  title(ws, `Correlation of returns: ${d.symbols.join(", ")}`, `${d.observations} observations · 1 = move together, 0 = unrelated, −1 = opposite`);
  header(ws, 4, ["", ...d.symbols]);
  const rng = (j: number) => `'${px.name}'!${col(n + 2 + j)}${first + 1}:${col(n + 2 + j)}${last}`;
  d.symbols.forEach((s: string, i: number) => {
    ws.getCell(`A${5 + i}`).value = s;
    ws.getCell(`A${5 + i}`).font = { bold: true };
    d.symbols.forEach((_: string, j: number) => formula(ws, `${col(j + 1)}${5 + i}`, `CORREL(${rng(i)},${rng(j)})`, d.matrix[i][j], "0.00"));
  });
  const v = 6 + n;
  label(ws, `A${v}`, "Annualised volatility", true);
  d.symbols.forEach((_: string, j: number) => formula(ws, `${col(j + 1)}${v}`, `STDEV.S(${rng(j)})*SQRT(${d.interval === "1d" ? 252 : 52})`, d.volatility[j], PCT));
  ws.getColumn(1).width = 24;
  for (let c = 2; c <= n + 1; c++) ws.getColumn(c).width = 14;
}

function dupont(wb: WB, d: any) {
  const ws = uniqueSheet(wb, `DuPont ${d.symbol}`);
  title(ws, `${d.symbol} · DuPont ROE analysis (${d.currency})`, "ROE = net margin × asset turnover × equity multiplier");
  header(ws, 4, ["Fiscal year end", ...d.years.map((y: any) => y.period)]);
  const rows: [string, (y: any, c: string) => any, string, boolean][] = [
    ["Net income", (y) => y.netIncome, BIG, true],
    ["Revenue", (y) => y.revenue, BIG, true],
    ["Total assets", (y) => y.totalAssets, BIG, true],
    ["Shareholders' equity", (y) => y.equity, BIG, true],
    ["Net margin", (_y, c) => `${c}5/${c}6`, PCT, false],
    ["Asset turnover", (_y, c) => `${c}6/${c}7`, "0.00", false],
    ["Equity multiplier (leverage)", (_y, c) => `${c}7/${c}8`, "0.00", false],
    ["ROE (product)", (_y, c) => `${c}9*${c}10*${c}11`, PCT, false],
    ["Check: net income ÷ equity", (_y, c) => `${c}5/${c}8`, PCT, false],
  ];
  const results = (y: any) => [null, null, null, null, y.netMargin, y.assetTurnover, y.equityMultiplier, y.roe, y.roe];
  rows.forEach(([l, fn, fmt, isInput], i) => {
    const row = 5 + i;
    label(ws, `A${row}`, l, !isInput && i >= 7);
    d.years.forEach((y: any, j: number) => {
      const c = col(j + 1), v = fn(y, c);
      if (isInput) input(ws, `${c}${row}`, v, fmt);
      else formula(ws, `${c}${row}`, v, results(y)[i], fmt, i === 7);
    });
  });
  ws.getColumn(1).width = 32;
  d.years.forEach((_: any, j: number) => (ws.getColumn(j + 2).width = 16));
}

/* ------------------------------ Generic ------------------------------ */

function generic(wb: WB, name: string, d: any) {
  const ws = uniqueSheet(wb, name);
  title(ws, name, "Data export");
  let row = 4;
  const scalars = Object.entries(d).filter(([, v]) => v == null || typeof v !== "object");
  const nested = Object.entries(d).filter(([, v]) => v && typeof v === "object" && !Array.isArray(v));
  const arrays = Object.entries(d).filter(([, v]) => Array.isArray(v));
  for (const [k, v] of scalars) { label(ws, `A${row}`, k); ws.getCell(`B${row++}`).value = v as any; }
  for (const [k, v] of nested) for (const [k2, v2] of Object.entries(v as object)) {
    label(ws, `A${row}`, `${k}.${k2}`);
    ws.getCell(`B${row++}`).value = v2 != null && typeof v2 === "object" ? JSON.stringify(v2) : (v2 as any);
  }
  for (const [k, arr] of arrays as [string, any[]][]) {
    if (!arr.length) continue;
    row++;
    label(ws, `A${row++}`, k, true);
    if (typeof arr[0] !== "object" || arr[0] === null) { ws.getCell(`A${row++}`).value = arr.join(", "); continue; }
    if (Array.isArray(arr[0])) { arr.forEach((r: any[]) => { r.forEach((v, j) => (ws.getCell(row, j + 1).value = v)); row++; }); continue; }
    const keys = [...new Set(arr.flatMap((o) => Object.keys(o)))];
    header(ws, row++, keys);
    for (const o of arr) { keys.forEach((kk, j) => { const v = o[kk]; ws.getCell(row, j + 1).value = v != null && typeof v === "object" ? JSON.stringify(v) : v; }); row++; }
  }
  ws.getColumn(1).width = 28;
  for (let c = 2; c <= 12; c++) ws.getColumn(c).width = 16;
}

/** Special case: comparison table becomes metrics × tickers. */
function compare(wb: WB, d: any) {
  const ws = uniqueSheet(wb, "Comparison");
  title(ws, `Comparison: ${d.symbols.map((s: any) => s.symbol).join(", ")}`, d.currencies ? `Currencies: ${d.currencies.join(", ")}` : "");
  header(ws, 4, ["Metric", ...d.symbols.map((s: any) => s.symbol)]);
  d.metrics.forEach((m: any, i: number) => {
    label(ws, `A${5 + i}`, m.label);
    m.values.forEach((v: any, j: number) => { const c = ws.getCell(5 + i, j + 2); c.value = v; c.numFmt = m.format === "percent" ? PCT : m.format === "large" ? BIG : NUM; });
  });
  ws.getColumn(1).width = 28;
}

const BUILDERS: Record<string, (wb: WB, d: any) => void> = {
  runDcfValuation: dcf,
  runComparableValuation: comps,
  runSipBacktest: sip,
  getRiskReturn: risk,
  getCorrelationMatrix: correlation,
  getDupontAnalysis: dupont,
  compareStocks: compare,
};

export function subjectOf(d: any): string {
  return d?.symbol ?? (Array.isArray(d?.symbols) ? d.symbols.map((s: any) => s?.symbol ?? s).slice(0, 3).join(" ") : d?.query ?? d?.region ?? d?.screen ?? "");
}

function addTool(wb: WB, toolName: string, data: any) {
  const b = BUILDERS[toolName];
  if (b) b(wb, data);
  else generic(wb, `${TOOL_LABELS[toolName] ?? toolName} ${subjectOf(data)}`.trim(), data);
}

async function newWorkbook() {
  const mod: any = await import("exceljs");
  const ExcelJSLib = (mod.default ?? mod) as typeof ExcelJS;
  const wb = new ExcelJSLib.Workbook();
  wb.creator = "Nazar";
  wb.created = new Date();
  wb.calcProperties.fullCalcOnLoad = true;
  return wb;
}

async function save(wb: WB, filename: string) {
  const buf = await wb.xlsx.writeBuffer();
  const blob = new Blob([buf], { type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename.replace(/[^\w.\- ]+/g, "_");
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 5000);
}

export async function downloadToolExcel(toolName: string, data: any) {
  const wb = await newWorkbook();
  addTool(wb, toolName, data);
  await save(wb, `StockAI ${TOOL_LABELS[toolName] ?? toolName} ${subjectOf(data)}.xlsx`.replace(/\s+/g, " "));
}

/** Every successful tool result in a conversation, one sheet (or model) each. Returns the count. */
export async function downloadChatExcel(parts: { toolName: string; data: any }[], title: string) {
  if (!parts.length) return 0;
  const wb = await newWorkbook();
  const index = wb.addWorksheet("Contents");
  index.getCell("A1").value = title || "Nazar research";
  index.getCell("A1").font = { bold: true, size: 14 };
  index.getCell("A2").value = `Generated by Nazar on ${new Date().toLocaleString()} · Blue cells are inputs, black cells are formulas · We explain; you decide. Not investment advice`;
  index.getCell("A2").font = { italic: true, color: { argb: "FF6B7280" }, size: 9 };
  header(index, 4, ["#", "Analysis", "Subject"]);
  parts.forEach((p, i) => {
    index.getCell(`A${5 + i}`).value = i + 1;
    index.getCell(`B${5 + i}`).value = TOOL_LABELS[p.toolName] ?? p.toolName;
    index.getCell(`C${5 + i}`).value = subjectOf(p.data);
    addTool(wb, p.toolName, p.data);
  });
  index.getColumn(2).width = 28;
  index.getColumn(3).width = 30;
  await save(wb, `StockAI ${title || "research"}.xlsx`.slice(0, 120));
  return parts.length;
}

/** For tests: build a workbook in memory (Node) without downloading. */
export async function buildWorkbookForTest(parts: { toolName: string; data: any }[]) {
  const wb = await newWorkbook();
  parts.forEach((p) => addTool(wb, p.toolName, p.data));
  return wb;
}
