"use client";
import type { UIMessage } from "ai";
import { FileDown, TrendingUp } from "lucide-react";
import Link from "next/link";
import { LocalTime } from "./LocalTime";
import { MessageList } from "./Messages";

/** Read-only view of a shared chat, at /s/<shareId>. */
export function SharedChat({ title, updatedAt, messages }: { title: string; updatedAt: string; messages: UIMessage[] }) {
  return (
    <div className="min-h-dvh">
      <header className="no-print sticky top-0 z-10 border-b border-zinc-800/80 bg-zinc-950/90 backdrop-blur">
        <div className="mx-auto flex max-w-3xl items-center justify-between gap-2 px-4 py-2.5">
          <Link href="/" className="flex items-center gap-2">
            <span className="flex h-7 w-7 items-center justify-center rounded-lg bg-emerald-500 text-zinc-950"><TrendingUp className="h-4 w-4" /></span>
            <span className="text-sm font-semibold">Stock AI</span>
          </Link>
          <div className="flex items-center gap-1.5">
            <button onClick={() => window.print()} className="flex items-center gap-1.5 rounded-lg border border-zinc-800 px-2.5 py-1.5 text-sm text-zinc-300 hover:bg-zinc-900">
              <FileDown className="h-4 w-4" /> PDF
            </button>
            <Link href="/" className="rounded-lg bg-emerald-500 px-3 py-1.5 text-sm font-medium text-zinc-950 hover:bg-emerald-400">Try Stock AI</Link>
          </div>
        </div>
      </header>
      <main className="mx-auto max-w-3xl px-4 pb-16 pt-6">
        <div className="mb-2 border-b border-zinc-800 pb-3">
          <h1 className="text-lg font-semibold text-zinc-100">{title}</h1>
          <div className="text-xs text-zinc-500">Shared research · last updated <LocalTime iso={updatedAt} /> · Market data may have changed since.</div>
        </div>
        <MessageList messages={messages} readOnly />
        <div className="mt-8 border-t border-zinc-800 pt-3 text-center text-[11px] text-zinc-600">Generated by Stock AI with Yahoo Finance data. Not investment advice.</div>
      </main>
    </div>
  );
}
