"use client";
import type { UIMessage } from "ai";
import { FileDown } from "lucide-react";
import Link from "next/link";
import { Wordmark } from "@/components/rings/nazar-mark";
import { buttonClass } from "@/components/ui/button";
import { LocalTime } from "./LocalTime";
import { MessageList } from "./Messages";

/** Read-only view of a shared Ask conversation, at /s/<shareId>. Portfolios are never shareable. */
export function SharedChat({ title, updatedAt, messages }: { title: string; updatedAt: string; messages: UIMessage[] }) {
  return (
    <div className="min-h-dvh">
      <header className="no-print sticky top-0 z-10 border-b border-line bg-bg/90 backdrop-blur">
        <div className="mx-auto flex max-w-3xl items-center justify-between gap-2 px-4 py-3">
          <Link href="/" aria-label="Nazar home">
            <Wordmark />
          </Link>
          <div className="flex items-center gap-2">
            <button onClick={() => window.print()} className={buttonClass("secondary", "sm")}>
              <FileDown className="h-4 w-4" /> PDF
            </button>
            <Link href="/" className={buttonClass("primary", "sm")}>
              Try Nazar
            </Link>
          </div>
        </div>
      </header>
      <main className="mx-auto max-w-3xl px-4 pb-16 pt-6">
        <div className="mb-2 border-b border-line pb-3">
          <h1 className="t-title-2 text-text">{title}</h1>
          <div className="t-caption">
            Shared from Nazar Ask · last updated <LocalTime iso={updatedAt} /> · Market data may have changed since.
          </div>
        </div>
        <MessageList messages={messages} readOnly />
        <div className="mt-8 border-t border-line pt-3 text-center text-[12px] text-subtle">Generated by Nazar with Yahoo Finance data. We explain; you decide. Not investment advice.</div>
      </main>
    </div>
  );
}
